[tool.poetry]
name = "9"
version = "0.1.0"
description = ""
authors = ["MrDWilson <d.wilson2306@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
